/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_openglstudyv2_CameraSGLNative */

#ifndef _Included_sen_opengl_camera_main_CameraSGLNative
#define _Included_sen_opengl_camera_main_CameraSGLNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_openglstudyv2_CameraSGLNative
 * Method:    initAssetManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_opengl_camera_main_CameraSGLNative_initAssetManager
  (JNIEnv *, jclass,jobject );

/*
 * Class:     sen_com_openglstudyv2_CameraSGLNative
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_opengl_camera_main_CameraSGLNative_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     sen_com_openglstudyv2_CameraSGLNative
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sen_opengl_camera_main_CameraSGLNative_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sen_com_openglstudyv2_CameraSGLNative
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_opengl_camera_main_CameraSGLNative_onDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     sen_com_openglstudyv2_CameraSGLNative
 * Method:    getSurfaceTexture
 * Signature: ()V
 */
JNIEXPORT jobject JNICALL Java_sen_opengl_camera_main_CameraSGLNative_getSurfaceTexture
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
