/* DO NOT EDIT THIS FILE - it is machine generated
 * 场景的头文件
 * */
#pragma once
#include "ggl.h"
#include "camera.h"
void init();
void setViewPortSize(float width ,float height);
//绘制场景
void draw();
Camera* beforInit(JNIEnv *env);




