/* DO NOT EDIT THIS FILE - it is machine generated
 * 加载文件的工具
 * */
#pragma once

#include "ggl.h"
#include "vertexbuffer.h"
#include "shader.h"
class Ground {
public:
    GLuint vbo;
    SShader *mShader;
    VertexBuffer *vertexBuffer;
    glm::mat4 mModelMatrix;

public:
    void init();//初始化数据
    void draw(glm::mat4 &mViewMatrix, glm::mat4 &mProjectionMatrix);
};






