/* DO NOT EDIT THIS FILE - it is machine generated
 * 加载文件的工具
 * */
#pragma once

#include "ggl.h"
#include "vertexbuffer.h"

class Ground {
    GLuint vbo;
    GLuint mProgram;
    VertexBuffer *vertexBuffer;
    GLint positionLocation,colorLocation, normalLocation ;
    GLint ProjectionMatrixLocation,ModelMatrixLocation, ViewMatrixLocation ;
public:
    void init();//初始化数据

};






