/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_openglstudyv2_SGLNative */

#ifndef _Included_sen_com_openglstudyv2_SGLNative
#define _Included_sen_com_openglstudyv2_SGLNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_openglstudyv2_SGLNative
 * Method:    initAssetManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_openglstudyv2_SGLNative_initAssetManager
  (JNIEnv *, jclass,jobject);

/*
 * Class:     sen_com_openglstudyv2_SGLNative
 * Method:    initOpengl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_openglstudyv2_SGLNative_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     sen_com_openglstudyv2_SGLNative
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sen_com_openglstudyv2_SGLNative_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sen_com_openglstudyv2_SGLNative
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_openglstudyv2_SGLNative_onDrawFrame
  (JNIEnv *, jclass);




#ifdef __cplusplus
}
#endif
#endif
